name: VulkanMenu
version: ${project.version}
main: com.vulkantechnologies.menu.VulkanMenu
api-version: '1.20'
libraries:
  - org.spongepowered:configurate-yaml:${configurate.version}
softdepend:
  - PlaceholderAPI
  - Vault
  - ItemsAdder
  - Oraxen
  - Nexo
  - packetevents
  - HeadDatabase