title: <rainbow>My cool menu
size: 18
open-command: trs
items:
  1:
    slot: 2
    item:
      material: "DIAMOND_SWORD"
      name: "My sword"
      lore:
        - "This is my sword"
        - "This is my sword"
    actions:
      - "[console] gamemode spectator <player>"
  2:
    slot: 4
    item:
      material: "DIAMOND_SWORD"
      name: "My sword"
      lore:
        - "This is my sword"
        - "This is my sword"
    actions:
      - "[player] say Hello"
    view-requirements:
      - "[permission] myplugin.command.hello"