title: <rainbow>My cool menu
size: 18
open-command: trs

open-requirements:
  permission:
    requirement: "[permission] myplugin.command.hello"
    deny-actions:
      - "[message] You don't have permission to use this item"
items:
  1:
    slot: 2
    item:
      material: "DIAMOND_SWORD"
      name: "My sword"
      lore:
        - "This is my sword"
        - "This is my sword"
    actions:
      - "[message] Hello"
  2:
    slot: 4
    item:
      material: "DIAMOND_SWORD"
      name: "My sword"
      lore:
        - "This is my sword"
        - "This is my sword"
    actions:
      - "[message] Hello"
    view-requirements:
      permission:
        requirement: "[permission] myplugin.command.hello"
        deny-actions:
          - "[message] You don't have permission to use this item"
