title: <rainbow>My cool menu
size: 18
open-command: trs
items:
  1:
    slot: 2
    item:
      type: "DIAMOND_SWORD"
      name: "My sword"
      lore:
        - "This is my sword"
        - "This is my sword"
  2:
    slot: 4
    item:
      type: "DIAMOND_SWORD"
      name: "My sword"
      lore:
        - "This is my sword"
        - "This is my sword"
